#!/usr/bin/env bash
#
# Портальный ключ — Interactive Setup
#
# This script prompts for all required configuration,
# writes .env, and starts the bot via Docker Compose.
#

set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

ENV_FILE=".env"

header() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  🔐 Портальный ключ — Установка${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

prompt() {
    local var_name="$1"
    local description="$2"
    local default_value="${3:-}"
    local is_secret="${4:-false}"
    local required="${5:-true}"

    if [ -n "$default_value" ]; then
        echo -e "${YELLOW}${description}${NC} [${default_value}]:"
    else
        echo -e "${YELLOW}${description}${NC}:"
    fi

    if [ "$is_secret" = "true" ]; then
        read -rs value
        echo ""
    else
        read -r value
    fi

    if [ -z "$value" ] && [ -n "$default_value" ]; then
        value="$default_value"
    fi

    if [ -z "$value" ] && [ -z "$default_value" ] && [ "$required" = "true" ]; then
        echo -e "${RED}  ✗ Это поле обязательно!${NC}"
        prompt "$var_name" "$description" "$default_value" "$is_secret" "$required"
        return
    fi

    printf -v "$var_name" '%s' "$value"
}

check_dependencies() {
    echo -e "${BOLD}Проверка зависимостей...${NC}"

    if command -v docker &>/dev/null; then
        echo -e "  ${GREEN}✓${NC} Docker установлен"
    else
        echo -e "  ${RED}✗ Docker не найден!${NC}"
        echo "  Установите Docker: https://docs.docker.com/engine/install/"
        exit 1
    fi

    if command -v docker compose &>/dev/null || command -v docker-compose &>/dev/null; then
        echo -e "  ${GREEN}✓${NC} Docker Compose установлен"
    else
        echo -e "  ${RED}✗ Docker Compose не найден!${NC}"
        echo "  Установите Docker Compose: https://docs.docker.com/compose/install/"
        exit 1
    fi

    echo ""
}

collect_config() {
    # --- Telegram ---
    echo -e "${BOLD}📱 Telegram${NC}"
    echo -e "  Получите токен бота у @BotFather в Telegram"
    prompt BOT_TOKEN "  BOT_TOKEN (токен бота)" "" "false"
    echo ""

    echo -e "  Узнайте свой Telegram ID у @userinfobot"
    prompt ADMIN_TELEGRAM_ID "  ADMIN_TELEGRAM_ID (ваш Telegram ID)" "" "false"
    echo ""

    # --- 3x-ui Panel ---
    echo -e "${BOLD}🖥️  3x-ui Panel${NC}"
    prompt XUI_URL "  XUI_URL (адрес панели, например https://your-server:2053)" "" "false"
    prompt XUI_USERNAME "  XUI_USERNAME (логин от панели)" "admin" "false"
    prompt XUI_PASSWORD "  XUI_PASSWORD (пароль от панели)" "" "true"
    prompt XUI_INBOUND_ID "  XUI_INBOUND_ID (ID inbound для VLESS клиентов)" "1" "false"
    echo ""

    # --- Server ---
    echo -e "${BOLD}🌐 Сервер${NC}"
    prompt SERVER_ADDRESS "  SERVER_ADDRESS (IP или домен для VLESS ссылок)" "" "false"
    echo ""

    # --- Subscription Plans ---
    echo -e "${BOLD}💰 Тарифы (в Telegram Stars)${NC}"
    prompt PLAN_1M_STARS "  1 месяц" "100" "false"
    prompt PLAN_3M_STARS "  3 месяца" "250" "false"
    prompt PLAN_6M_STARS "  6 месяцев" "450" "false"
    prompt PLAN_12M_STARS "  12 месяцев" "800" "false"
    echo ""

    # --- Optional ---
    echo -e "${BOLD}⚙️  Дополнительно (Enter для значений по умолчанию)${NC}"
    prompt TRAFFIC_LIMIT_GB "  Лимит трафика GB (0 = безлимит)" "0" "false"
    prompt REFERRAL_BONUS_STARS "  Реферальный бонус Stars" "10" "false"
    prompt NOTIFY_BEFORE_DAYS "  Дни напоминаний через запятую" "3,1" "false"
    prompt RATE_LIMIT_PER_MINUTE "  Лимит запросов в минуту" "30" "false"
    prompt SUPPORT_USERNAME "  Username поддержки (без @, Enter чтобы пропустить)" "" "false" "false"
    echo ""

    # --- Database ---
    echo -e "${BOLD}🗄️  База данных${NC}"
    prompt DATABASE_URL "  DATABASE_URL" "sqlite+aiosqlite:///./vpn_bot.db" "false"
    echo ""
}

write_env() {
    echo -e "${BOLD}Записываю .env ...${NC}"

    (umask 077; cat > "$ENV_FILE" <<EOF
# ============================
# Портальный ключ — Configuration
# Generated by setup.sh
# ============================

# --- Telegram ---
BOT_TOKEN=${BOT_TOKEN}
ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}

# --- Database ---
DATABASE_URL=${DATABASE_URL}

# --- 3x-ui Panel ---
XUI_URL=${XUI_URL}
XUI_USERNAME=${XUI_USERNAME}
XUI_PASSWORD=${XUI_PASSWORD}
XUI_INBOUND_ID=${XUI_INBOUND_ID}

# --- Server ---
SERVER_ADDRESS=${SERVER_ADDRESS}

# --- Subscription Plans (Telegram Stars) ---
PLAN_1M_STARS=${PLAN_1M_STARS}
PLAN_3M_STARS=${PLAN_3M_STARS}
PLAN_6M_STARS=${PLAN_6M_STARS}
PLAN_12M_STARS=${PLAN_12M_STARS}

# --- Traffic ---
TRAFFIC_LIMIT_GB=${TRAFFIC_LIMIT_GB}

# --- Referral System ---
REFERRAL_BONUS_STARS=${REFERRAL_BONUS_STARS}

# --- Notifications ---
NOTIFY_BEFORE_DAYS=${NOTIFY_BEFORE_DAYS}

# --- Rate Limiting ---
RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE}

# --- Support ---
SUPPORT_USERNAME=${SUPPORT_USERNAME}
EOF
    )

    echo -e "  ${GREEN}✓${NC} .env создан (права: 600)"
}

start_bot() {
    echo ""
    echo -e "${BOLD}🚀 Запуск бота...${NC}"

    if command -v docker compose &>/dev/null; then
        docker compose up -d --build
    else
        docker-compose up -d --build
    fi

    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  ✅ Портальный ключ запущен!${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "  Логи:     ${CYAN}docker compose logs -f vpn-bot${NC}"
    echo -e "  Стоп:     ${CYAN}docker compose down${NC}"
    echo -e "  Рестарт:  ${CYAN}docker compose restart${NC}"
    echo ""
    echo -e "  Откройте бота в Telegram и отправьте ${BOLD}/start${NC}"
    echo ""
}

# --- Main ---
header

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  Файл .env уже существует.${NC}"
    echo -n "Перезаписать? (y/N): "
    read -r overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Используем существующий .env"
        start_bot
        exit 0
    fi
    echo ""
fi

check_dependencies
collect_config
write_env
start_bot
